

export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOK_DETAIL_SUCCESS = 'GET_BOOK_DETAIL_SUCCESS';
export const GET_CHARCTERS_SUCCESS = 'GET_CHARCTERS_SUCCESS';
export const GET_CHARACTER_DETAIL_SUCCESS = 'GET_CHARACTER_DETAIL_SUCCESS';
export const GET_HOUSES_SUCCESS = 'GET_HOUSES_SUCCESS';
export const GET_HOUSE_DETAIL_SUCCESS = 'GET_HOUSE_DETAIL_SUCCESS';
export const GET_OVERLORD_SUCCESS = 'GET_OVERLORD_SUCCESS';
export const GET_FOUNDER_SUCCESS = 'GET_FOUNDER_SUCCESS';
export const GET_CURRENT_LORD_SUCCESS = 'GET_CURRENT_LORD_SUCCESS';
export const GET_SWORN_SUCCESS = 'GET_SWORN_SUCCESS';